name: freebsd_build

on: [push]

jobs:
  build:
    runs-on: macos-10.15
    name: A job to run test FreeBSD
    # env:
    steps:
    - uses: actions/checkout@v2
    - name: Build in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v0.1.5
      with:
        # envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        sync: sshfs
        prepare: pkg install -y curl libevent cmake argp-standalone
        run: |
          pwd
          freebsd-version
          mkdir build
          cd build
          cmake ../
          make
